version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27028:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - my_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - network.host=0.0.0.0
      - http.host=0.0.0.0
      - xpack.license.self_generated.type=trial
      - xpack.security.enabled=false
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./data/esdata:/usr/share/elasticsearch/data
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  mongodb_data_container:
